package models

import (
	"time"

	goshopify "github.com/bold-commerce/go-shopify"
	"github.com/malalwan/slaash/internal/helpers"
	"github.com/shopspring/decimal"
)

// User is the user model
type User struct {
	ID          int
	FirstName   string
	LastName    string
	Email       string
	Password    string
	AccessLevel int
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	Store       helpers.Store
}

type Campaign struct {
	CampaignID   int64         // autogen unique campaignID (PK)
	Store        helpers.Store // store for which the campaign is set
	Timestamp    *time.Time    // activation time of campaign (nothing if not)
	Discount     int           // overall discount in % of total price
	ActiveStatus int           // 1 : active, 2 : assigned, 3 : fulfilled(mail sent)
	Misc         string        // extra details if needed
}

// Structure that stores price
// rules created by slaash
type PriceRule struct {
	Title             string
	TargetType        string
	TargetSelection   string
	ValueType         string
	Value             *decimal.Decimal
	CustomerSelection string
	AllocationMethod  string
	StartsAt          *time.Time
}

// Structure that stores discount
// codes generated by slaash
type DiscountCode struct {
	ID          int64
	PriceRuleID int64
	Code        string
	UsageCount  int
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// Details of the Products added
// to the deal list cumulatively
type CampaignProduct struct {
	ID           int64             // auto gen PK
	CampaignID   int64             // FK to Campaign
	ProductID    int64             // Product ID of the given product (to fetch from shopify)
	Title        string            // product title for local storage
	ProductType  string            // Review if needed
	Status       string            // Review if needed
	Images       []goshopify.Image // product image list for seamless dahsboard display (linked, not stored)
	Store        helpers.Store     // easy access to the store for initiating connection to shopify
	Deals        int               // stores the number of deals on a specific product (init as 1)
	Sold         int               // number of campaign products sold (get from order data)
	DealDiscount int               // If a deal was given on the product or not
	EmailSentTo  []string          // List of emails who recieved the deal (till date)
	Misc         string            // Extra info whenever needed
	PriceRuleID  int64             // Price rule associated with the discount
}

// Structure to store email IDs when end
// user subscribes to deal list
type Buyer struct {
	AnonymousID int64         // PK
	Email       string        // Also Unique
	Store       helpers.Store // Store details on which the deal list was clicked
	ProductId   int64         // Product ID of the product added to the deal list
	Timestamp   *time.Time    // Subscription timestamp
	GotDeal     bool          // Initialized as false, unless campaign fulfilled
	ClickedDeal bool          // Initialized as false, set when Buyer clicks on checkout link
	CPID        int64         // FK to CampaignProduct DB where deals increment will happen
	Misc        string        // Extra info about the buyer
}

func GetActiveCampaign(helpers.Store) (*Campaign, error) {
	// pull active campaign(s) for a store from DB
	// return the campaign
	return &Campaign{
		CampaignID: 0,
	}, nil
}

func GetCampaignProducts(*Campaign) ([]CampaignProduct, error) {
	// pull all campaign products with the given campaing ID from DB
	return []CampaignProduct{CampaignProduct{}}, nil
}

func CreateCampaign(helpers.Store) (*Campaign, error) {
	return &Campaign{}, nil
}

func CreateCampaignProducts(*Campaign) ([]CampaignProduct, error) {
	return []CampaignProduct{}, nil
}

func GetCampaignByID(int64) (*Campaign, error) {
	return &Campaign{}, nil
}

func UpdateCampaignProducts(*Campaign) ([]CampaignProduct, error) {
	return []CampaignProduct{}, nil
}

func ListAllCampaigns() ([]Campaign, error) {
	return []Campaign{}, nil
}
